INSERT INTO availability (room_type_id, date, available_count, price)
SELECT rt.id, d.dt, 5, 4500.00
FROM room_types rt
JOIN (
  SELECT CURDATE() + INTERVAL seq DAY AS dt
  FROM (
    SELECT 0 AS seq UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
    UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9
    UNION ALL SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13
  ) s
) d ON 1=1
WHERE rt.code = 'DLX'
ON DUPLICATE KEY UPDATE available_count = VALUES(available_count), price = VALUES(price);

INSERT INTO availability (room_type_id, date, available_count, price)
SELECT rt.id, d.dt, 3, 3800.00
FROM room_types rt
JOIN (
  SELECT CURDATE() + INTERVAL seq DAY AS dt
  FROM (
    SELECT 0 AS seq UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
    UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9
    UNION ALL SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13
  ) s
) d ON 1=1
WHERE rt.code = 'STU'
ON DUPLICATE KEY UPDATE available_count = VALUES(available_count), price = VALUES(price);
